# Generated by Django 5.0.1 on 2024-01-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_show_episode_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='one.show')),
            ],
        ),
    ]
