# Generated by Django 5.0.1 on 2024-01-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='show',
            new_name='re',
        ),
        migrations.AddField(
            model_name='season',
            name='seasonNum',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
