# Generated by Django 5.0.1 on 2024-01-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_rename_show_season_re_season_seasonnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='re',
            new_name='show',
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='one.season'),
        ),
    ]
