# Generated by Django 5.0.1 on 2024-01-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_rename_re_season_show_episode_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='tags',
            field=models.ManyToManyField(blank=True, to='one.tag'),
        ),
    ]
