# Generated by Django 5.0.1 on 2024-01-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_tag_episode_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
