# Generated by Django 5.0.1 on 2024-01-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_rename_tag_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
