# Generated by Django 5.0.1 on 2024-01-26 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0008_rename_tags_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mp4_file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('hls_folder', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HLS_Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('epNum', models.IntegerField()),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('folder_path', models.CharField(max_length=1000)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='one.season')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='one.show')),
                ('tags', models.ManyToManyField(blank=True, to='one.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
