# Generated by Django 5.0.1 on 2024-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0009_video_hls_folder_delete_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
