# Generated by Django 5.0.1 on 2024-01-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0011_remove_hls_folder_folder_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HLS_Folder',
            new_name='Video',
        ),
    ]
