# Generated by Django 5.0.1 on 2024-01-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0012_rename_hls_folder_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
